#!/usr/bin/env bash
USERNAME='root'
PASSWORD=''
DBNAME='db_starswar'
HOST='localhost'

USER_USERNAME='lionel'
USER_PASSWORD='lionel'

MySQL=$(cat <<EOF
DROP DATABASE IF EXISTS $DBNAME;
CREATE DATABASE $DBNAME DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
DELETE FROM mysql.user WHERE user='$USER_USERNAME' and host='$USER_PASSWORD';
GRANT ALL PRIVILEGES ON $DBNAME.* to '$USER_USERNAME'@'$HOST' IDENTIFIED BY '$USER_PASSWORD' WITH GRANT OPTION;
EOF
)

php artisan migrate:refresh --seed